/*
 * This source file was generated by the Gradle 'init' task
 */
package testcases;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    public void testMajority() {
        App app = new App();
        int[] nums1 = {3, 3, 4, 2, 3};
        int[] nums2 = {1, 2, 3, 2, 2, 2};
        
        assertEquals(3, app.majority(nums1));
        assertEquals(2, app.majority(nums2));
    }

    @Test
    public void testRotatedSearch() {
        App app = new App();
        int[] rotatedArray1 = {4, 5, 6, 7, 0, 1, 2};
        int[] rotatedArray2 = {6, 7, 8, 1, 2, 3, 4, 5};
        
        assertEquals(4, app.rotatedSearch(rotatedArray1, 0));
        assertEquals(-1, app.rotatedSearch(rotatedArray1, 3));
        assertEquals(3, app.rotatedSearch(rotatedArray2, 1));
    }

    @Test
    public void testHasCycle() {
        App app = new App();
        
        ListNode head = new ListNode(1);
        ListNode node2 = new ListNode(2);
        ListNode node3 = new ListNode(3);
        head.next = node2;
        node2.next = node3;
        node3.next = node2; // Creates a cycle

        assertTrue(app.hasCycle(head));

        ListNode noCycleHead = new ListNode(1);
        noCycleHead.next = new ListNode(2);
        assertFalse(app.hasCycle(noCycleHead));
    }

    @Test
    public void testRemoveDuplicates() {
        App app = new App();
        
        assertEquals("ad", app.removeDuplicates("abccbd"));
        assertEquals("ca", app.removeDuplicates("abbaca"));
        assertEquals("", app.removeDuplicates("aa"));
    }
}
